### ISSUE TITLE
dimensions or models of the green an purple parts?

### ISSUE THREAD

**Issue by roadfox** [sergey-prokhorov/YAY#1]
Hi found your interesting design today and started printing the parts.

While looking ate the plans i could not find out how to create the gree and purple parts shown in plan.png.
Can you provide drawings with dimensions for those elements as well?

**Comment by sergey-prokhorov** [comment]
hello! sorry for lazy answer. green and purple parts should be made from foam.

**Comment by sergey-prokhorov** [comment]
all printable parts are orange.

**Comment by roadfox** [comment]
Hi Sergey, thanks for your respond, but where do i get the shape for the puprle parts from?

**Comment by sergey-prokhorov** [comment]
easiest way to make this parts is use this printable patterns:
https://github.com/sergey-prokhorov/YAY/blob/master/stl/pattern%203.stl
https://github.com/sergey-prokhorov/YAY/blob/master/stl/pattern%204.stl
https://github.com/sergey-prokhorov/YAY/blob/master/stl/pattern%205.stl

**Comment by sergey-prokhorov** [comment]
You can message me via facebook this is more faster communication way
